# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0007_auto_20171026_0221'),
        ('bfd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConclaveScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('lacerating_claws', models.IntegerField(default=0)),
                ('kimbul_wrath', models.IntegerField(default=0)),
                ('kragwa_wrath', models.IntegerField(default=0)),
                ('static_orb', models.IntegerField(default=0)),
                ('paku_wrath', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='RhastakhanScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('deathly_withering', models.IntegerField(default=0)),
                ('toads', models.IntegerField(default=0)),
                ('seal_of_purification', models.IntegerField(default=0)),
                ('plague_of_fire', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
    ]
