# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-17 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfd', '0003_championscore_grongscore_jadefirescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='grongscore',
            name='deathly_echo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grongscore',
            name='not_running_out_throw',
            field=models.IntegerField(default=0),
        ),
    ]
