# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-19 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfd', '0004_auto_20190217_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='opulencescore',
            name='flame_jets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opulencescore',
            name='lasers',
            field=models.IntegerField(default=0),
        ),
    ]
