# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-20 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0007_auto_20171026_0221'),
        ('bfd', '0005_auto_20190219_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockadeScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('voltaic_flash', models.IntegerField(default=0)),
                ('sea_swell', models.IntegerField(default=0)),
                ('sea_storm', models.IntegerField(default=0)),
                ('torrential_swell', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='JainaScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('avalanche', models.IntegerField(default=0)),
                ('glacial_ray', models.IntegerField(default=0)),
                ('glacial_shards', models.IntegerField(default=0)),
                ('icefall', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='MekkatorqueScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('buster_cannon', models.IntegerField(default=0)),
                ('blastoff', models.IntegerField(default=0)),
                ('trample', models.IntegerField(default=0)),
                ('failed_bots', models.IntegerField(default=0)),
                ('sheep', models.IntegerField(default=0)),
                ('gigavolt_blast', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
    ]
