# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfd', '0006_blockadescore_jainascore_mekkatorquescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclavescore',
            name='raptor_damage',
            field=models.IntegerField(default=0),
        ),
    ]
