# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-10 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfd', '0008_mekkatorquescore_radiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockadescore',
            name='voltaic_flash',
        ),
        migrations.AddField(
            model_name='jainascore',
            name='bombards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jainascore',
            name='ice_blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jainascore',
            name='standing_in_fire',
            field=models.IntegerField(default=0),
        ),
    ]
