# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-24 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfd', '0009_auto_20190410_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jainascore',
            old_name='glacial_shards',
            new_name='broadside',
        ),
        migrations.AddField(
            model_name='jainascore',
            name='freezing_blast',
            field=models.IntegerField(default=0),
        ),
    ]
