# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WoWRaidScore', '0007_auto_20171026_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggramarScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('soaking_combo', models.IntegerField(default=0)),
                ('flare_damage', models.IntegerField(default=0)),
                ('blaze_damage', models.IntegerField(default=0)),
                ('wake_of_flame', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='ArgusScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('bomb_burst_damage', models.IntegerField(default=0)),
                ('death_fog', models.IntegerField(default=0)),
                ('scythe', models.IntegerField(default=0)),
                ('cosmic_ray', models.IntegerField(default=0)),
                ('ember_of_rage', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='CovenScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('storm_damage', models.IntegerField(default=0)),
                ('norgannon', models.IntegerField(default=0)),
                ('khazgoroth', models.IntegerField(default=0)),
                ('golganoth', models.IntegerField(default=0)),
                ('whirlwind', models.IntegerField(default=0)),
                ('orb_of_frost', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='EonarScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('rain_of_fire_splash', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='FelhoundsScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('molten_flare', models.IntegerField(default=0)),
                ('consuming_sphere', models.IntegerField(default=0)),
                ('desolate_path', models.IntegerField(default=0)),
                ('enflamed', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='HighCommandScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('step_on_mines', models.IntegerField(default=0)),
                ('bladestorm', models.IntegerField(default=0)),
                ('good_use_of_pod', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='ImonarScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('stepping_on_mines', models.IntegerField(default=0)),
                ('sleep_canister', models.IntegerField(default=0)),
                ('charged_blasts', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='KingarothScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('ruiner', models.IntegerField(default=0)),
                ('annihilation_soaks', models.IntegerField(default=0)),
                ('destruction_soaks', models.IntegerField(default=0)),
                ('decimation', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='PortalKeeperScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('felstorm_barrage', models.IntegerField(default=0)),
                ('missed_orb_pickup', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='VerimathrasScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('bad_embrace', models.IntegerField(default=0)),
                ('bad_arrows', models.IntegerField(default=0)),
                ('fissure', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='WorldbreakerScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('annihilation_soaks', models.IntegerField(default=0)),
                ('hit_from_laser', models.IntegerField(default=0)),
                ('decimation', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
    ]
