# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antorus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covenscore',
            old_name='orb_of_frost',
            new_name='shadowblades',
        ),
    ]
