# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antorus', '0002_auto_20171204_0116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerimathrasScore',
            new_name='VarimathrasScore',
        ),
    ]
