# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('zone_id', models.IntegerField()),
                ('boss_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_id', models.IntegerField()),
                ('percent', models.FloatField()),
                ('killed', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WoWRaidScore.Boss')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('server', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_id', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RaidScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.IntegerField()),
                ('melee_dps', models.BooleanField()),
                ('ranged_dps', models.BooleanField()),
                ('tank', models.BooleanField()),
                ('healer', models.BooleanField()),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WoWRaidScore.Fight')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WoWRaidScore.Player')),
            ],
        ),
        migrations.AddField(
            model_name='fight',
            name='raid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WoWRaidScore.Raid'),
        ),
    ]
