# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='attempt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
