# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0004_auto_20171011_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='last_analyzer_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fight',
            name='date_parsed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
