# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0005_auto_20171023_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
