# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0007_auto_20171026_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightevent',
            name='score_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
