# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WoWRaidScore', '0009_auto_20190712_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzsharaScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('sanction', models.IntegerField(default=0)),
                ('beckon', models.IntegerField(default=0)),
                ('detonation', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
    ]
