# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azshara_palace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azsharascore',
            name='drained_soul',
            field=models.IntegerField(default=0),
        ),
    ]
