# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistressscore',
            name='stacked_hydra_shots',
            field=models.IntegerField(default=0),
        ),
    ]
