# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0002_mistressscore_stacked_hydra_shots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistressscore',
            name='bufferfish_uptime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mistressscore',
            name='murlock_debuff_uptime',
            field=models.IntegerField(default=0),
        ),
    ]
