# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0002_fight_attempt'),
        ('tos', '0003_auto_20170928_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidenScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('wrong_color', models.IntegerField(default=0)),
                ('wrong_orb', models.IntegerField(default=0)),
                ('didnt_jump_in_hole', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.RemoveField(
            model_name='gorothscore',
            name='spike_damage',
        ),
        migrations.AlterField(
            model_name='gorothscore',
            name='not_hiding',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gorothscore',
            name='soaking_infernals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gorothscore',
            name='splashing_from_meteors',
            field=models.IntegerField(default=0),
        ),
    ]
