# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0005_auto_20171005_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistressscore',
            old_name='interupts',
            new_name='interrupts',
        ),
    ]
