# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0004_auto_20171011_0236'),
        ('tos', '0006_auto_20171005_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarjatanScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('soaking_slams', models.IntegerField(default=0)),
                ('stacks_of_debuff', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
        migrations.CreateModel(
            name='SistersScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('glaive_storm', models.IntegerField(default=0)),
                ('twilight_glaive', models.IntegerField(default=0)),
                ('astral_vuln', models.IntegerField(default=0)),
                ('lunar_beacon', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
    ]
