# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0004_auto_20171011_0236'),
        ('tos', '0007_harjatanscore_sistersscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('dissonance', models.IntegerField(default=0)),
                ('break_armors', models.IntegerField(default=0)),
                ('soulbinds', models.IntegerField(default=0)),
                ('rupturing_slam', models.IntegerField(default=0)),
                ('tormented_cries', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
    ]
