# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WoWRaidScore', '0004_auto_20171011_0236'),
        ('tos', '0008_hostscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIScore',
            fields=[
                ('raidscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WoWRaidScore.RaidScore')),
                ('interrupts', models.IntegerField(default=0)),
                ('grouping_jail', models.IntegerField(default=0)),
                ('explosive_anguish', models.IntegerField(default=0)),
                ('times_in_jail', models.IntegerField(default=0)),
            ],
            bases=('WoWRaidScore.raidscore',),
        ),
    ]
